tasks:
  - init: |
      echo "Installing Firebase tools..."
      npm install -g firebase-tools
      cd /workspace/ha_client_fcf/functions
      echo "Getting dependencies..."
      npm install
      echo "Logging in..."
      firebase login:ci

    command: |
      cd /workspace/ha_client_fcf/functions
      echo "Make sure we are using the latest versions of Firebase tools and libraries..."
      npm install firebase-functions@latest firebase-admin@latest --save
      npm install -g firebase-tools
